# functions/__init__.py
from .calcTargetIncome import calculate_inflation_adjusted_income
from .calculateAccumulation import calculate_yearly_buildup
from .calculateAnnuity import calculate_annuity_payments
from .calculateNPV import calculate_npv
from .optimiseContribution import optimise_contribution
